apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: traefik-forward-auth-secrets
    namespace: cert-manager
    envs:
    - traefik-forward-auth.env
    type: Opaque
    options:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "traefik"

generatorOptions:
  disableNameSuffixHash: true

resources:
  - traefik-forward-auth-deployment.yaml
  - traefik-forward-auth-ingress.yaml