---
## AUTHENTICATION ##
# Using Traefik-Forward-Auth linked back to Entra ID
# See https://github.com/thomseddon/traefik-forward-auth for examples & details
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: traefik
  labels:
    app: traefik-forward-auth
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll            
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/match-tag: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: traefik-forward-auth
        image: thomseddon/traefik-forward-auth:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
          seccompProfile:
            type: RuntimeDefault
        imagePullPolicy: Always
        ports:
        - containerPort: 4181
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        env:
        - name: DEFAULT_PROVIDER
          value: oidc
        - name: PROVIDERS_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: client-id
        - name: PROVIDERS_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: client-secret
        - name: PROVIDERS_OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: issuer-url
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: secret
        - name: WHITELIST
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: whitelist
        - name: COOKIE_DOMAIN
          value: "timo.be"
        - name: DOMAIN
          value: "timo.be"
        - name: AUTH_HOST
          value: "auth.timo.be"
        - name: INSECURE_COOKIE
          value: "false"
        - name: LOG_LEVEL
          value: "info"