# Service so that gatus can connect to Cloudflare Tunnel for monitoring
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-kubernetes
  namespace: utilities
spec:
  ports:
    - name: http
      port: 2000
      targetPort: 2000
  selector:
    app.kubernetes.io/name: cloudflared-kubernetes