# Apply all these resources with `kubectl apply -k .` from the directory containing this file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: cloudflare-tunnel-token-kubernetes
    namespace: utilities
    envs:
      - cloudflare-tunnel-token-kubernetes.env
    type: Opaque

generatorOptions:
 disableNameSuffixHash: true
 
resources:
  - cloudflare-tunnel.yaml
  - cloudflare-service.yaml