---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bentopdf-traefik
  namespace: utilities
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bentopdf.kubernetes.timo.be`) || Host(`bentopdf.timo.be`)
      kind: Rule
      services:
        - name: bentopdf
          port: 8080
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bentopdf-tailscale
  namespace: utilities
  annotations:
    # Instead of exposing as a machine, expose it as a Tailscale Service
    tailscale.com/proxy-group: tailscale-services
spec:
  defaultBackend:
    service:
      name: bentopdf
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - bentopdf