# Apply all these resources with `kubectl apply -k .` from the directory containing this file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utilities

resources:
  - epicgames-freegames.yaml
  - epicgames-freegames-network.yaml

configMapGenerator:
  - name: epicgames-freegames-config
    namespace: utilities
    files:
      - config.json=config.json
    options:
      labels:
        app.kubernetes.io/name: epicgames-freegames

secretGenerator:
  - name: epicgames-freegames-secrets
    namespace: utilities
    envs:
      - epicgames-freegames-secrets.env
    type: Opaque
    options:
      labels:
        app.kubernetes.io/name: epicgames-freegames

generatorOptions:
  disableNameSuffixHash: true