globalArguments:
  - "--global.sendanonymoususage"

logs:
  general:
    level: INFO
  access:
    enabled: true
    format: json
    fields:
      defaultMode: keep
      headers:
        defaultMode: drop
    filters:
      statuscodes: "400-499,500-599"
      retryattempts: true

deployment:
  enabled: true
  replicas: 3

ports:
  web:
    # Setting port manually to 8001 since portaineredge uses port 8000, otherwise default helm chat values will use 8000
    port: 8001
    expose:
      default: false
    redirections:
      entryPoint: 
        to: websecure
        scheme: https
        permanent: true
  traefik:
    port: 9000
    exposedPort: 9000
    protocol: TCP
  websecure:
    port: 8443
    expose:
      default: true
    asDefault: true
    exposedPort: 443
    protocol: TCP
    # Necessary for VNC and other apps to work without issues. Otherwise you get connection and timeout issues.
    # See https://community.traefik.io/t/traefik-vnc-web-apps-works-in-docker-but-not-in-kubernetes/27180/2
    transport:
      respondingTimeouts:
        readTimeout: 420s
        writeTimeout: 420s
        idleTimeout: 420s
    tls:
      enabled: true
    # middlewares:
    #   - traefik-secureheaders@kubernetescrd
    #   - traefik-ratelimit@kubernetescrd
  metrics:
    port: 9100
    expose:
      default: true
    exposedPort: 9100
    protocol: TCP
  portaineredge:
    port: 8000
    expose:
      default: false
    exposedPort: 8000
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    namespaces: []
    allowCrossNamespace: true
    allowExternalNameServices: true
    ingressClass: traefik

  kubernetesIngress:
    enabled: true
    namespaces: []
    ingressClass: traefik
    allowExternalNameServices: true
    publishedService:
      enabled: true

dashboard:
  enabled: true

rbac:
  enabled: true
  
# Will define my own services because I want to expose traefik both through tailscale and through kube-vip
service:
  enabled: false