apiVersion: v1
kind: PersistentVolume
metadata:
  name: games-roms-pv
  namespace: utilities
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.local.timo.be
    path: /mnt/X.A.N.A./media/games/roms
  mountOptions:
    - vers=4.2
    - relatime
    - sec=sys
    - hard
    - rw
    - nolock

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: switchkeys-pv
  namespace: utilities
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.local.timo.be
    path: /mnt/X.A.N.A./media/games/switch/switchkeys
  mountOptions:
    - vers=4.2
    - relatime
    - sec=sys
    - hard
    - rw
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games-roms-pvc
  namespace: utilities
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  volumeName: games-roms-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: switchkeys-pvc
  namespace: utilities
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: switchkeys-pv
