---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gatus
  namespace: utilities
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gatus.kubernetes.timo.be`) || Host(`gatus.timo.be`)
      kind: Rule
      services:
        - name: gatus
          port: 8080
          sticky:
            cookie:
              secure: true
              httpOnly: true
              sameSite: none
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus-tailscale
  namespace: utilities
  annotations:
    # Instead of exposing as a machine, expose it as a Tailscale Service
    tailscale.com/proxy-group: tailscale-services
spec:
  defaultBackend:
    service:
      name: gatus
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - gatus
