# Apply all these resources with `kubectl apply -k .` from the directory containing this file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: gatus
    namespace: utilities
    files:
      - storage.yaml
      - endpoints.yaml
      - alerting.yaml
      - maintenance.yaml
      - settings.yaml
    options:
      labels:
        app.kubernetes.io/name: gatus

secretGenerator:
  - name: gatus-secrets
    namespace: utilities
    envs:
      - gatus-secrets.env
    type: Opaque
    options:
      labels:
        app.kubernetes.io/name: gatus

generatorOptions:
  disableNameSuffixHash: true

resources:
  - gatus-serviceaccount.yaml
  - gatus.yaml
  - gatus-ingress.yaml
  - gatus-service.yaml