---
apiVersion: v1
kind: Service
metadata:
  name: iventoy-kubevip
  namespace: utilities
spec:
  selector:
    app.kubernetes.io/name: iventoy
  loadBalancerClass: kube-vip.io/kube-vip-class
  type: LoadBalancer
  loadBalancerIP: 10.10.10.38
  ports:
  - name: tftp
    protocol: UDP
    port: 69
    targetPort: tftp
  - name: pxe
    protocol: TCP
    port: 16000
    targetPort: pxe
  - name: nbd
    protocol: TCP
    port: 10809
    targetPort: nbd
  - name: webui
    protocol: TCP
    port: 26000
    targetPort: webui
---
apiVersion: v1
kind: Service
metadata:
  name: iventoy-traefik
  namespace: utilities
spec:
  selector:
    app.kubernetes.io/name: iventoy
  ports:
    - name: webui
      protocol: TCP
      port: 26000
      targetPort: webui