apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: subgen-secrets
    namespace: mediaplayback
    envs:
      - subgen-secrets.env
    type: Opaque
    options:
      labels:
        app.kubernetes.io/name: subgen

resources:
  - subgen.yaml
  - subgen-network.yaml
