---
apiVersion: v1
kind: Service
metadata:
  name: subgen-kubevip
  namespace: mediaplayback
spec:
  selector:
    app.kubernetes.io/name: subgen
  loadBalancerClass: kube-vip.io/kube-vip-class
  type: LoadBalancer
  loadBalancerIP: 10.10.10.41
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
