apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Custom Ingresses - Other Hosts
  - traefik-dashboard.yaml
  - traefik-dns.yaml
  - traefik-proxmox.yaml
  - traefik-dawarich.yaml
  - traefik-webtop.yaml
  - traefik-scrutiny.yaml

  # Custom Ingresses - TheFactory Media
  - traefik-sonarr.yaml
  - traefik-radarr.yaml
  - traefik-bazarr.yaml
  - traefik-prowlarr.yaml
  - traefik-yamtrack.yaml
  - traefik-dispatcharr.yaml
  - traefik-tautulli.yaml
  - traefik-wrapperr.yaml
  - traefik-obzorarr.yaml

  # Custom Ingresses - TheFactory Downloaders
  - traefik-qbittorrent.yaml
  - traefik-jdownloader2.yaml
  - traefik-metube.yaml
  - traefik-ariang.yaml
  - traefik-spotdl.yaml

  # Custom Ingresses - TheFactory Filemanagement
  - traefik-doublecommander.yaml
  - traefik-filezilla.yaml

  # Custom Ingresses - Traefik API for homepage
  - traefik-api.yaml