apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    # API → no auth
    - match: ( Host(`radarr.timo.be`) || Host(`radarr.kubernetes.timo.be`) ) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: radarr-svc
          port: 14001

    # SignalR → no auth
    - match: ( Host(`radarr.timo.be`) || Host(`radarr.kubernetes.timo.be`) ) && PathPrefix(`/signalr`)
      kind: Rule
      services:
        - name: radarr-svc
          port: 14001

    # Everything else → auth
    - match: ( Host(`radarr.timo.be`) || Host(`radarr.kubernetes.timo.be`) ) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: radarr-svc
          port: 14001
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 14001
      targetPort: 14001
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: radarr-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: radarr-svc
addressType: IPv4
ports:
  - port: 14001
endpoints:
  - addresses:
      - "10.10.10.2"
    conditions:
      ready: true