apiVersion: v1
kind: Service
metadata:
  name: metube-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 12002
      targetPort: 12002
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: metube-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: metube-svc
addressType: IPv4
ports:
  - port: 12002
endpoints:
  - addresses:
      - "10.10.10.2"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metube
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`metube.kubernetes.timo.be`) || Host(`metube.timo.be`)
      kind: Rule
      services:
        - name: metube-svc
          port: 12002
      middlewares:
        - name: auth
          namespace: traefik