apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    # API → no auth
    - match: ( Host(`bazarr.timo.be`) || Host(`bazarr.kubernetes.timo.be`) ) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: bazarr-svc
          port: 14002

    # Everything else → auth
    - match: ( Host(`bazarr.timo.be`) || Host(`bazarr.kubernetes.timo.be`) ) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: bazarr-svc
          port: 14002
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 14002
      targetPort: 14002
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: bazarr-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: bazarr-svc
addressType: IPv4
ports:
  - port: 14002
endpoints:
  - addresses:
      - "10.10.10.2"
    conditions:
      ready: true