apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tautulli
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    # API → no auth
    - match: ( Host(`tautulli.timo.be`) || Host(`tautulli.kubernetes.timo.be`) ) && PathPrefix(`/api/v2`)
      kind: Rule
      services:
        - name: tautulli-svc
          port: 14009

    # Everything else → auth
    - match: ( Host(`tautulli.timo.be`) || Host(`tautulli.kubernetes.timo.be`) ) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: tautulli-svc
          port: 14009
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 14009
      targetPort: 14009
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: tautulli-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: tautulli-svc
addressType: IPv4
ports:
  - port: 14009
endpoints:
  - addresses:
      - "10.10.10.2"
    conditions:
      ready: true
