apiVersion: v1
kind: Service
metadata:
  name: spotdl-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 12005
      targetPort: 12005
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: spotdl-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: spotdl-svc
addressType: IPv4
ports:
  - port: 12005
endpoints:
  - addresses:
      - "10.10.10.2"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spotdl
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`spotdl.kubernetes.timo.be`) || Host(`spotdl.timo.be`)
      kind: Rule
      services:
        - name: spotdl-svc
          port: 12005
      middlewares:
        - name: auth
          namespace: traefik