---
apiVersion: v1
kind: Service
metadata:
  name: doublecommander-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 13002
      targetPort: 13002
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: doublecommander-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: doublecommander-svc
addressType: IPv4
ports:
  - port: 13002
endpoints:
  - addresses:
      - "10.10.10.2"
    conditions:
      ready: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: doublecommander
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`doublecommander.kubernetes.timo.be`) || Host(`doublecommander.timo.be`)
      kind: Rule
      services:
        - name: doublecommander-svc
          port: 13002
      middlewares:
        - name: auth
          namespace: traefik