apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dispatcharr
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dispatcharr.kubernetes.timo.be`) || Host(`dispatcharr.timo.be`)
      kind: Rule
      services:
        - name: dispatcharr-svc
          port: 14008
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcharr-svc
  namespace: traefik
spec:
  externalName: thefactory.local.timo.be # Can also be an IP address
  type: ExternalName
