apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dispatcharr
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dispatcharr.kubernetes.timo.be`) || Host(`dispatcharr.timo.be`)
      kind: Rule
      services:
        - name: dispatcharr-svc
          port: 14008
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcharr-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 14008
      targetPort: 14008
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: dispatcharr-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: dispatcharr-svc
addressType: IPv4
ports:
  - port: 14008
endpoints:
  - addresses:
      - "10.10.10.2"
