apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wrapperr
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wrapperr.kubernetes.timo.be`) || Host(`wrapperr.timo.be`)
      kind: Rule
      services:
        - name: wrapperr-svc
          port: 14010
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: wrapperr-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 14010
      targetPort: 14010
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: wrapperr-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: wrapperr-svc
addressType: IPv4
ports:
  - port: 14010
endpoints:
  - addresses:
      - "10.10.10.2"
    conditions:
      ready: true
