apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: yamtrack
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`yamtrack.kubernetes.timo.be`) || Host(`yamtrack.timo.be`)
      kind: Rule
      services:
        - name: yamtrack-svc
          port: 14006
      middlewares:
        - name: auth
          namespace: traefik
---
# API Endpoint (only in local network) so that plex & other services in same local network can reach it
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: yamtrack-api
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`yamtrackapi.kubernetes.timo.be`)
      kind: Rule
      services:
        - name: yamtrack-svc
          port: 14006
---
apiVersion: v1
kind: Service
metadata:
  name: yamtrack-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 14006
      targetPort: 14006
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: yamtrack-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: yamtrack-svc
addressType: IPv4
ports:
  - port: 14006
endpoints:
  - addresses:
      - "10.10.10.2"