apiVersion: v1
kind: Service
metadata:
  name: filezilla-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 13001
      targetPort: 13001
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: filezilla-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: filezilla-svc
addressType: IPv4
ports:
  - port: 13001
endpoints:
  - addresses:
      - "10.10.10.2"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filezilla
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`filezilla.kubernetes.timo.be`) || Host(`filezilla.timo.be`)
      kind: Rule
      services:
        - name: filezilla-svc
          port: 13001
      middlewares:
        - name: auth
          namespace: traefik