apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dawarich
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dawarich.kubernetes.timo.be`) || Host(`dawarich.timo.be`)
      kind: Rule
      services:
        - name: dawarich-svc
          port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dawarich-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: dawarich-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: dawarich-svc
addressType: IPv4
ports:
  - port: 3000
endpoints:
  - addresses:
      - "10.10.10.2"
    conditions:
      ready: true
