apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    # API → no auth
    - match: ( Host(`prowlarr.timo.be`) || Host(`prowlarr.kubernetes.timo.be`) ) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: prowlarr-svc
          port: 14004

    # SignalR → no auth
    - match: ( Host(`prowlarr.timo.be`) || Host(`prowlarr.kubernetes.timo.be`) ) && PathPrefix(`/signalr`)
      kind: Rule
      services:
        - name: prowlarr-svc
          port: 14004

    # Everything else → auth
    - match: ( Host(`prowlarr.timo.be`) || Host(`prowlarr.kubernetes.timo.be`) ) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: prowlarr-svc
          port: 14004
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 14004
      targetPort: 14004
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: prowlarr-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: prowlarr-svc
addressType: IPv4
ports:
  - port: 14004
endpoints:
  - addresses:
      - "10.10.10.2"