apiVersion: v1
kind: Service
metadata:
  name: ariang-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 12003
      targetPort: 12003
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ariang-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: ariang-svc
addressType: IPv4
ports:
  - port: 12003
endpoints:
  - addresses:
      - "10.10.10.2"
    conditions:
      ready: true
---
apiVersion: v1
kind: Service
metadata:
  name: ariangrpc-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 12004
      targetPort: 12004
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ariangrpc-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: ariangrpc-svc
addressType: IPv4
ports:
  - port: 12004
endpoints:
  - addresses:
      - "10.10.10.2"
    conditions:
      ready: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ariang
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ariang.kubernetes.timo.be`) || Host(`ariang.timo.be`)
      kind: Rule
      services:
        - name: ariang-svc
          port: 12003
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ariangrpc
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: (Host(`ariang.kubernetes.timo.be`) || Host(`ariang.timo.be`)) && PathPrefix(`/jsonrpc`)
      kind: Rule
      services:
        - name: ariangrpc-svc
          port: 12004
      middlewares:
        - name: auth
          namespace: traefik
