apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: huntarr
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`huntarr.kubernetes.timo.be`) || Host(`huntarr.timo.be`)
      kind: Rule
      services:
        - name: huntarr-svc
          port: 14005
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: huntarr-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 14005
      targetPort: 14005
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: huntarr-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: huntarr-svc
addressType: IPv4
ports:
  - port: 14005
endpoints:
  - addresses:
      - "10.10.10.2"