apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: scrutiny
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`scrutiny.kubernetes.timo.be`) || Host(`scrutiny.timo.be`)
      kind: Rule
      services:
        - name: scrutiny-svc
          port: 31054
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: scrutiny-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 31054
      targetPort: 31054
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: scrutiny-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: scrutiny-svc
addressType: IPv4
ports:
  - port: 31054
endpoints:
  - addresses:
      - "10.10.10.2"
    conditions:
      ready: true