apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webtop
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`webtop.kubernetes.timo.be`) || Host(`webtop.timo.be`)
      kind: Rule
      services:
        - name: webtop-svc
          port: 12006
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: webtop-svc
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 12006
      targetPort: 12006
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: webtop-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: webtop-svc
addressType: IPv4
ports:
  - port: 12006
endpoints:
  - addresses:
      - "10.10.10.2"
