---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tinshop-traefik
  namespace: switchutilities
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tinshop.kubernetes.timo.be`)
      kind: Rule
      services:
        - name: tinshop
          port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tinshop
  namespace: switchutilities
spec:
  selector:
    app: tinshop
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
