# Apply all these resources with `kubectl apply -k .` from the directory containing this file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: plex-secrets
    namespace: mediaplayback
    envs:
      - plex-secrets.env
    type: Opaque
    options:
      labels:
        app.kubernetes.io/name: plex

resources:
  - rbac.yaml
  - plex.yaml
  - plex-storage.yaml
  - plex-autolanguages.yaml
  - plex-network.yaml