---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv
  namespace: mediaplayback
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 10.10.10.2:3260
    iqn: iqn.2025-11.timo.be:plex
    lun: 0
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: mediaplayback
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  volumeName: plex-pv