---
# Service to expose all of plex's relevant ports to the local network for DLNA/device discovery and playback
apiVersion: v1
kind: Service
metadata:
  name: plex-kubevip
  namespace: mediaplayback
spec:
  selector:
    app.kubernetes.io/name: plex
  loadBalancerClass: kube-vip.io/kube-vip-class
  type: LoadBalancer
  loadBalancerIP: 10.10.10.39
  ports:
  - name: plex
    protocol: TCP
    port: 32400
  - name: gdm0
    protocol: UDP
    port: 32410
    targetPort: 32410
  - name: gdm1
    protocol: UDP
    port: 32412
    targetPort: 32412
  - name: gdm2
    protocol: UDP
    port: 32413
    targetPort: 32413
  - name: gdm3
    protocol: UDP
    port: 32414
    targetPort: 32414
---
# Service to be used by Traefik and Tailscale Ingress to access plex Web UI
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: mediaplayback
spec:
  ports:
    - name: plex
      port: 32400
      protocol: TCP
      targetPort: 32400
  selector:
    app.kubernetes.io/name: plex
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: mediaplayback
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.kubernetes.timo.be`) || Host(`plex.timo.be`)
      kind: Rule
      services:
        - name: plex
          port: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-tailscale
  namespace: mediaplayback
  annotations:
    # Instead of exposing as a machine, expose it as a Tailscale Service
    tailscale.com/proxy-group: tailscale-services
spec:
  defaultBackend:
    service:
      name: plex
      port:
        number: 32400
  ingressClassName: tailscale
  tls:
    - hosts:
        - plex
