---
# Non-Authenticated IngressRoute for local network access
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ersatztv-authless
  namespace: mediaplayback
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ersatztv.kubernetes.timo.be`)
      kind: Rule
      services:
        - name: ersatztv
          port: 8409
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ersatztv-authenticated
  namespace: mediaplayback
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ersatztv.timo.be`)
      kind: Rule
      services:
        - name: ersatztv
          port: 8409
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ersatztv-tailscale
  namespace: mediaplayback
  annotations:
    # Instead of exposing as a machine, expose it as a Tailscale Service
    tailscale.com/proxy-group: tailscale-services
spec:
  defaultBackend:
    service:
      name: ersatztv
      port:
        number: 8409
  ingressClassName: tailscale
  tls:
    - hosts:
        - ersatztv
