apiVersion: v1
kind: Service
metadata:
  name: ersatztv
  namespace: mediaplayback
spec:
  ports:
    - name: http
      port: 8409
      protocol: TCP
      targetPort: 8409
  selector:
    app.kubernetes.io/name: ersatztv
