---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netbootxyz-traefik
  namespace: utilities
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`netbootxyz.kubernetes.timo.be`) || Host(`netbootxyz.timo.be`)
      kind: Rule
      services:
        - name: netbootxyz-traefik
          port: 3000
      middlewares:
        - name: auth
          namespace: traefik