---
apiVersion: v1
kind: Service
metadata:
  name: netbootxyz-kubevip
  namespace: utilities
spec:
  selector:
    app.kubernetes.io/name: netbootxyz
  loadBalancerClass: kube-vip.io/kube-vip-class
  type: LoadBalancer
  loadBalancerIP: 10.10.10.37
  ports:
  - name: tftp
    protocol: UDP
    port: 69
    targetPort: tftp
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: webui
    protocol: TCP
    port: 3000
    targetPort: webui
---
apiVersion: v1
kind: Service
metadata:
  name: netbootxyz-traefik
  namespace: utilities
spec:
  selector:
    app.kubernetes.io/name: netbootxyz
  ports:
    - name: webui
      protocol: TCP
      port: 3000
      targetPort: webui