---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie
  namespace: utilities
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mealie.kubernetes.timo.be`) || Host(`mealie.timo.be`)
      kind: Rule
      services:
        - name: mealie
          port: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie-tailscale
  namespace: utilities
  annotations:
    # Instead of exposing as a machine, expose it as a Tailscale Service
    tailscale.com/proxy-group: tailscale-services
spec:
  defaultBackend:
    service:
      name: mealie
      port:
        number: 9000
  ingressClassName: tailscale
  tls:
    - hosts:
        - mealie
