---
apiVersion: v1
kind: Service
metadata:
  name: whisper-asr-webservice-kubevip
  namespace: whisper-asr-webservice
spec:
  selector:
    app.kubernetes.io/name: whisper-asr-webservice
  loadBalancerClass: kube-vip.io/kube-vip-class
  type: LoadBalancer
  loadBalancerIP: 10.10.10.41
  ports:
  - name: whisper
    protocol: TCP
    port: 9000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: whisper-asr-webservice
#   namespace: whisper-asr-webservice
# spec:
#   selector:
#     app: whisper-asr-webservice
#   ports:
#   - name: whisper
#     protocol: TCP
#     port: 9000
#     targetPort: whisper
