---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-test-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 10.10.10.9:3260
    iqn: iqn.2025-12.be.timo.local.odd:iscsi-test
    lun: 0
    fsType: ext4
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-test-pvc
  namespace: iscsi-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: iscsi-test-pv
