# Apply all these resources with `kubectl kustomize --enable-helm . | kubectl apply -f -` from the directory containing this file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
 disableNameSuffixHash: true

resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/refs/heads/main/cmd/k8s-operator/deploy/manifests/operator.yaml
  - tailscale-proxygroup.yaml

secretGenerator:
  - name: operator-oauth
    namespace: cert-manager
    envs:
    - tailscale.env
    type: Opaque
    options:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "tailscale"

patches:
  # Add autoupdate through keel for tailscale-operator
  - target:
      kind: Deployment
      name: operator
      namespace: tailscale
    path: tailscale-operator-patch-deployment.yaml

  # Delete the operator-oauth secret, as I create it separately
  - target:
      kind: Secret
      name: operator-oauth
      namespace: tailscale
    path: tailscale-operator-patch-delete-secret.yaml
  
  # Add necessary permissions to the namespace for Tailscale to work
  - target:
      kind: Namespace
      name: tailscale
    path: tailscale-namespace.yaml