# Allow tailscale devices tagged with "tag:github-cicd" cluster-admin access for Tailscale Kubernetes API server proxy access
# See https://tailscale.com/kb/1437/kubernetes-operator-api-server-proxy#impersonating-kubernetes-groups-with-tagged-tailnet-nodes
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-api-tailscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: tag:github-cicd
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: verbrugghet@gmail.com
  apiGroup: rbac.authorization.k8s.io