# A proxyGroup needs to be defined to route to Tailscale Services (instead of creating a tailscale machine for a service)
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: tailscale-services
spec:
  type: ingress
---
# A proxyGroup to access the Kubernetes API server through Tailscale
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: sectorfive-api
spec:
  type: kube-apiserver
  replicas: 3
  tags: ["tag:k8s-api"]
  kubeAPIServer:
    mode: auth