---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stirlingpdf-traefik
  namespace: stirlingpdf
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`stirlingpdf.kubernetes.timo.be`) || Host(`stirlingpdf.timo.be`)
      kind: Rule
      services:
        - name: stirlingpdf
          port: 8080
      middlewares:
        - name: auth
          namespace: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirlingpdf-tailscale
  namespace: stirlingpdf
  annotations:
    # Instead of exposing as a machine, expose it as a Tailscale Service
    tailscale.com/proxy-group: tailscale-services
spec:
  defaultBackend:
    service:
      name: stirlingpdf
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - stirlingpdf