apiVersion: v1
kind: ConfigMap
metadata:
  name: tinshop-config
  namespace: utilities
data:
  config.yaml: |
    host: tinshop.kubernetes.timo.be
    protocol: https
    reverseProxy: true
    keys: /switchkeys/prod.keys
    name: TinShop
    nowelcomemessage: false
    nsp:
      checkverified: false
    renamefiles: false
    security:
      bannedtheme: []
      blacklist: []
      forwardauth: ""
      hauth: ""
      whitelist: []
    sources:
      directories:
        - /games
      nfs: []
    welcomemessage: Welcome to Timo Tinshop!
